#+title:  CV
#+author: Ankit Kumar

* Contact Info
Khoury College of Computer Sciences, Northeastern University, Boston
Phone: +1 (857) 869 5430
Email: ankitkumar.itbhu@gmail.com
Website: https://ankitku.github.io 
LinkedIn: ankitkumar1988
Github: ankitku

* Professional Summary
Experienced Applied Scientist with a background in finance and tech
industries, having worked at Rivos, Amazon, Morgan Stanley and
Olacabs. During my tenure as a software developer in India, I was
highly interested in types and property based testing. Pursuing this
passion, I earned a PhD in formal methods, equipping myself with tools
and techniques required to ensure software reliability and
correctness. I am now eager to leverage my academic expertise and
industry experience to implement formal methods in practical
applications, driving innovation and enhancing software quality in
real-world projects.

* Education

** Northeastern University Boston, MA, USA
PhD in Computer Science 2018–2024

Applied theorem proving, counter-example generation and the theory of
refinement to analyze the Gossipsub P2P protocol. Also worked on
automated feedback for homework submissions, proof checking and
decision procedures for solving string equations.

*Thesis:* Refinement based reasoning of P2P protocols is feasible and
useful 

** IIT Kanpur, Kanpur, UP, India, 2015–2017
M.Tech in Computer Science 

** IIT (BHU) Varanasi, Varanasi, UP, India, 2006-2010
B.Tech in Electrical Engineering 

* Professional Experience

** Rivos Inc. Portland, OR, USA, Summer 2023
Member of Technical Staff, Intern 

Formalized and proved security properties about the page walk
algorithm and certain chip components using the ACL2s theorem prover.

** Amazon Minneapolis, MN, USA, Summer 2022
Applied Scientist Intern 

Proposed and demonstrated using taint-analysis for cloud level
tracking of critical data across AWS resources.

** Olacabs Bengaluru, KA, India, 2012-2014
Software Development Engineer II 

Wrote the first version of the Olacabs android consumer app. Worked on
performance enhancement of the Olacabs driver app which sends the
location of cab to backend services. Worked on cashless payment and
online wallet systems.

** Morgan Stanley Advantage Services Mumbai, MH, India
Associate 2010-2012

Planned and enabled the Third Party Derivatives trading platform at
Morgan Stanley to be rolled out to new markets by making its code
region aware, modular and pluggable.

* Publications
- Ankit Kumar, Max von Hippel, Panagiotis Manolios & Cristina
  Nita-Rotaru (2023): Verification of GossipSub in ACL2s. In:
  Proceedings of the 18th International Workshop on the ACL2 Theorem
  Prover and Its Applications, doi:10.4204/EPTCS.393.10. Available at
  https://doi.org/10.4204/ EPTCS.393.10.

- Ankit Kumar, Max von Hippel, Panagiotis Manolios & Cristina
  Nita-Rotaru (2024): Formal Model-Driven Analysis of Resilience of
  GossipSub to Attacks from Misbehaving Peers. In: 2024 IEEE Symposium
  on Security and Privacy (SP),
  doi:10.1109/SP54263.2024.00017. Available at
  https://doi.ieeecomputersociety.org/10.1109/SP54263.2024.00017.

- Ankit Kumar & Panagiotis Manolios (2021): Mathematical Programming
  Modulo Strings. In: 2021 Formal Methods in Computer Aided Design
  (FMCAD), doi:10.34727/2021/isbn.978-3-85448-046-4. Available at
  https://doi.org/10.34727/2021/isbn.978-3-85448-046-4_36.

- Ankit Kumar, Andrew Walter & Panagiotis Manolios (2023): Automated
  Grading of Automata with ACL2s. Electronic Proceedings in
  Theoretical Computer Science, doi:10.4204/eptcs.375.7. Available at
  http://dx.doi.org/10.4204/EPTCS.375.7.

- Andrew T. Walter, Ankit Kumar & Panagiotis Manolios (2023):
  Calculational Proofs in ACL2s. CoRR abs/2307.12224,
  doi:10.48550/ARXIV.2307.12224. arXiv:2307.12224.

- Andrew T. Walter, Ankit Kumar & Panagiotis Manolios (2023): Proving
  Calculational Proofs Correct. In: Proceedings of the 18th
  International Workshop on the ACL2 Theorem Prover and Its
  Applications, doi:10.4204/EPTCS.393.11. Available at
  https://doi.org/10.4204/EPTCS.393.11.

* Computer Skills
Reasoning, Formal Proofs, Mechanical Verification and Validation,
SAT, SMT, BDD, Z3, CVC4, CVC5,
C, C++, Java, Rust, Lisp, ACL2, ACL2s, Coq, Agda, Haskell, Emacs, Git,
LATEX


* Awards and Honors
- Fellowship: Dissertation Completion Fellowship during Summer 2024.
- Invited Talk - Syracuse University 2024: Formal Model-Driven
  Analysis of Resilience of GossipSub
to Attacks from Misbehaving Peers
- Award: Best Student Paper Award for our paper “Verification of
  GossipSub in ACL2s” at ACL2 Workshop 2023.
- Invited Talk - IPFS Camp at Lisbon, 2022: Formal Analysis of
  GossipSub : Property Driven Dev for Security
- Fellowship: Student Travel Fellowship to attend PLMW at POPL 2019
  conference. Award: First Prize at Droidcon India - Bangalore 2013
  Hackathon
